
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'B929DC9810A54D168AC86EA0166D5B18'
    
_lr_action_items = {'RPAREN':([3,4,7,8,9,10,11,],[-2,-1,-4,11,-3,-5,-6,]),'LPAREN':([0,1,2,3,4,5,6,7,8,9,10,11,],[2,2,2,-2,2,2,2,-4,2,-3,-5,-6,]),'DASH':([1,3,4,7,8,9,10,11,],[5,-2,5,-4,5,-3,5,-6,]),'CHAR':([0,1,2,3,4,5,6,7,8,9,10,11,],[3,3,3,-2,3,3,3,-4,3,-3,-5,-6,]),'UNION':([1,3,4,7,8,9,10,11,],[6,-2,6,-4,6,-3,-5,-6,]),'$end':([1,3,4,7,9,10,11,],[0,-2,-1,-4,-3,-5,-6,]),'STAR':([1,3,4,7,8,9,10,11,],[7,-2,7,-4,7,7,7,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,1,2,4,5,6,8,9,10,],[1,4,8,4,9,10,4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr expr','expr',2,'p_expr_concat','P2.py',35),
  ('expr -> CHAR','expr',1,'p_expr_char','P2.py',38),
  ('expr -> expr DASH expr','expr',3,'p_expr_dash','P2.py',41),
  ('expr -> expr STAR','expr',2,'p_expr_star','P2.py',44),
  ('expr -> expr UNION expr','expr',3,'p_expr_union','P2.py',48),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_group','P2.py',51),
  ('statement -> expr','statement',1,'p_statement_expr','P2.py',54),
]
