
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '3FF43A3631BDD47AD5F3ED19F7F962F1'
    
_lr_action_items = {'STAR':([1,4,6,7,8,11,],[6,-5,-6,6,-8,-7,]),'UNION':([1,2,4,5,6,7,8,9,11,12,],[-3,-1,-5,10,-6,-4,-8,10,-7,-2,]),'RPAREN':([1,2,3,4,6,7,8,9,11,12,],[-3,-1,8,-5,-6,-4,-8,11,-7,-2,]),'LPAREN':([0,1,2,3,4,6,7,8,10,11,12,],[3,-3,3,3,-5,-6,-4,-8,3,-7,3,]),'CHAR':([0,1,2,3,4,6,7,8,10,11,12,],[4,-3,4,4,-5,-6,-4,-8,4,-7,4,]),'$end':([1,2,4,5,6,7,8,11,12,],[-3,-1,-5,0,-6,-4,-8,-7,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'chunk':([0,3,10,],[2,2,12,]),'term':([0,2,3,10,12,],[1,7,1,1,7,]),'expr':([0,3,],[5,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> chunk','expr',1,'p_expr_chunk','P2.py',65),
  ('expr -> expr UNION chunk','expr',3,'p_expr_union','P2.py',68),
  ('chunk -> term','chunk',1,'p_chunk_term','P2.py',72),
  ('chunk -> chunk term','chunk',2,'p_chunk_concat','P2.py',75),
  ('term -> CHAR','term',1,'p_term_char','P2.py',79),
  ('term -> term STAR','term',2,'p_term_star','P2.py',82),
  ('term -> LPAREN expr RPAREN','term',3,'p_term_group','P2.py',85),
  ('term -> LPAREN RPAREN','term',2,'p_term_epsilon','P2.py',89),
]
